const questions=[
    {
        varname:"mfq_1",
        questiontext:"Caring for people who have suffered is an important virtue.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_2",
        questiontext:"I believe that compassion for those who are suffering is one of the most crucial virtues.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_3",
        questiontext:"We should all care for people who are in emotional pain.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_4",
        questiontext:"I am empathetic toward those people who have suffered in their lives.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_5",
        questiontext:"Everyone should try to comfort people who are going through something hard.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_6",
        questiontext:"It pains me when I see someone ignoring the needs of another human being.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_7",
        questiontext:"The world would be a better place if everyone made the same amount of money.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_8",
        questiontext:"Our society would have fewer problems if people had the same income.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_9",
        questiontext:"I believe that everyone should be given the same quantity of resources in life.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_10",
        questiontext:"I believe it would be ideal if everyone in society wound up with roughly the same amount of money.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree" 
    },
    {
        varname:"mfq_11",
        questiontext:"When people work together toward a common goal, they should share the rewards equally, even if some worked harder on it.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_12",
        questiontext:"I get upset when some people have a lot more money than others in my country.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_13",
        questiontext:"I think people who are more hard-working should end up with more money.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_14",
        questiontext:"I think people should be rewarded in proportion to what they contribute.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_15",
        questiontext:"The effort a worker puts into a job ought to be reflected in the size of a raise they receive.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_16",
        questiontext: "It makes me happy when people are recognized on their merits.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_17",
        questiontext:"In a fair society, those who work hard should live with higher standards of living.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_18",
        questiontext:"I feel good when I see cheaters get caught and punished.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_19",
        questiontext:"I think children should be taught to be loyal to their country.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_20",
        questiontext:"It upsets me when people have no loyalty to their country.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_21",
        questiontext:"Everyone should love their own community.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_22",
        questiontext:"Everyone should defend their country, if called upon.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_23",
        questiontext:"Everyone should feel proud when a person in their community wins in an international competition.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_24",
        questiontext:"I believe the strength of a sports team comes from the loyalty of its members to each other.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_25",
        questiontext:"I think it is important for societies to cherish their traditional values.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_26",
        questiontext:"I feel that most traditions serve a valuable function in keeping society orderly.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_27",
        questiontext:"I think obedience to parents is an important virtue.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_28",
        questiontext:"We all need to learn from our elders.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_29",
        questiontext:"I believe that one of the most important values to teach children is to have respect for authority.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_30",
        questiontext:"I think having a strong leader is good for society.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_31",
        questiontext:"I think the human body should be treated like a temple, housing something sacred within.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_32",
        questiontext:"I believe chastity is an important virtue.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_33",
        questiontext:"It upsets me when people use foul language like it is nothing.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_34",
        questiontext:"If I found out that an acquaintance had an unusual but harmless sexual fetish I would feel uneasy about them.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_35",
        questiontext:"People should try to use natural medicines rather than chemically identical human-made ones.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    },
    {
        varname:"mfq_36",
        questiontext:"I admire people who keep their virginity until marriage.",
        option1:"Strongly Disagree",
        option2:"Disagree",
        option3:"Slightly Disagree",
        option4:"Neutral",
        option5:"Slightly Agree",
        option6:"Agree",
        option7:"Strongly Agree"
    }
]

export default questions;

